### ISSUE TITLE
Avocado Leaves threw up error

### ISSUE THREAD

**Issue by Neo-Qwerty** [mrsterner/Cultural-Delights-Fabric#20]
The avocado leaves threw me a rather long error in my output log:

> [Worker-Main-8/ERROR]: Couldn't parse element loot_tables:culturaldelights:blocks/avocado_leaves
com.google.gson.JsonSyntaxException: Unknown type 'minecraft:alternative'
	at net.minecraft.class_5330$class_5333.deserialize(class_5330.java:99) ~[client-intermediary.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1290) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179) ~[gson-2.10.jar:?]
	at net.minecraft.class_3518.method_15291(class_3518.java:463) ~[client-intermediary.jar:?]
	at net.minecraft.class_3518.method_15283(class_3518.java:481) ~[client-intermediary.jar:?]
	at net.minecraft.class_79$class_5337.method_29319(class_79.java:85) ~[client-intermediary.jar:?]
	at net.minecraft.class_79$class_5337.method_517(class_79.java:74) ~[client-intermediary.jar:?]
	at net.minecraft.class_5330$class_5333.deserialize(class_5330.java:102) ~[client-intermediary.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1290) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179) ~[gson-2.10.jar:?]
	at net.minecraft.class_3518.method_15291(class_3518.java:463) ~[client-intermediary.jar:?]
	at net.minecraft.class_3518.method_15272(class_3518.java:471) ~[client-intermediary.jar:?]
	at net.minecraft.class_69$1.method_29313(class_69.java:61) ~[client-intermediary.jar:?]
	at net.minecraft.class_69$1.method_424(class_69.java:53) ~[client-intermediary.jar:?]
	at net.minecraft.class_79$class_5337.method_29319(class_79.java:86) ~[client-intermediary.jar:?]
	at net.minecraft.class_79$class_5337.method_517(class_79.java:74) ~[client-intermediary.jar:?]
	at net.minecraft.class_5330$class_5333.deserialize(class_5330.java:102) ~[client-intermediary.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1290) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179) ~[gson-2.10.jar:?]
	at net.minecraft.class_3518.method_15291(class_3518.java:463) ~[client-intermediary.jar:?]
	at net.minecraft.class_3518.method_15272(class_3518.java:471) ~[client-intermediary.jar:?]
	at net.minecraft.class_55$class_57.method_358(class_55.java:173) ~[client-intermediary.jar:?]
	at net.minecraft.class_55$class_57.deserialize(class_55.java:169) ~[client-intermediary.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1290) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179) ~[gson-2.10.jar:?]
	at net.minecraft.class_3518.method_15291(class_3518.java:463) ~[client-intermediary.jar:?]
	at net.minecraft.class_3518.method_15283(class_3518.java:481) ~[client-intermediary.jar:?]
	at net.minecraft.class_52$class_54.method_340(class_52.java:250) ~[client-intermediary.jar:?]
	at net.minecraft.class_52$class_54.deserialize(class_52.java:246) ~[client-intermediary.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1261) ~[gson-2.10.jar:?]
	at net.minecraft.class_8490.method_51205(class_8490.java:64) ~[client-intermediary.jar:?]
	at net.minecraft.class_8490.method_51204(class_8490.java:48) ~[client-intermediary.jar:?]
	at net.minecraft.class_60.method_51195(class_60.java:55) ~[client-intermediary.jar:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at net.minecraft.class_60.method_51189(class_60.java:55) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]

**Comment by ytcalifax** [comment]
Getting the same issue, any updates on the situation?

**Comment by mrsterner** [comment]
This is such an old issue, sheesh, i can check it out if i can recreate the issue
