### ISSUE TITLE
Error in recipe Fabric 1.20.1

### ISSUE THREAD

**Issue by YOUNIN15** [mrsterner/Cultural-Delights-Fabric#32]
An error with a recipe appears in the server log.

Fabric 0.15.11
Minecraft 1.20.1

https://mclo.gs/n3dGgM3

![image](https://github.com/user-attachments/assets/e9d4f131-c292-4f54-b50b-af2c72246145)

**Comment by ToshiNamura** [comment]
I have the same problem, it doesn't crash the game, but it clearly symbolizes that something is broken.
**Minecraft version:** _1.20.1_
**Fabric loader version:** _0.16.2_
**Mod version:** _1.0.5+1.20.1 [Refabricated]_
```
Parsing error loading recipe culturaldelights:fermenting/pickle
com.google.gson.JsonSyntaxException: Unknown item 'c:foods/vegetables/cucumber'
	at net.minecraft.class_1869.method_17878(class_1869.java:272)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at net.minecraft.class_1869.method_8155(class_1869.java:272)
	at net.minecraft.class_1856.method_8107(class_1856.java:160)
	at net.minecraft.class_1856.method_8102(class_1856.java:143)
	at net.minecraft.class_1856.method_52177(class_1856.java:135)
	at dev.sterner.brewinandchewin.common.recipe.KegRecipe$Serializer.readIngredients(KegRecipe.java:180)
	at dev.sterner.brewinandchewin.common.recipe.KegRecipe$Serializer.fromJson(KegRecipe.java:150)
	at dev.sterner.brewinandchewin.common.recipe.KegRecipe$Serializer.method_8121(KegRecipe.java:144)
	at net.minecraft.class_1863.method_17720(class_1863.java:135)
	at net.minecraft.class_1863.method_20705(class_1863.java:56)
	at net.minecraft.class_1863.method_18788(class_1863.java:35)
	at net.minecraft.class_4080.method_18790(class_4080.java:13)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_4014.method_18365(class_4014.java:69)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.class_1255.method_18857(class_1255.java:139)
	at net.minecraft.class_310.method_18857(class_310.java:23017)
	at net.minecraft.class_7196.method_45694(class_7196.java:188)
	at net.minecraft.class_7196.method_41891(class_7196.java:123)
	at net.minecraft.class_7196.method_41899(class_7196.java:202)
	at net.minecraft.class_7196.handler$zop000$bclib$wt_callFixerOnLoad(class_7196.java:546)
	at net.minecraft.class_7196.method_41894(class_7196.java)
	at net.minecraft.class_528$class_4272.method_20174(class_528.java:590)
	at net.minecraft.class_528$class_4272.method_20164(class_528.java:480)
	at net.minecraft.class_528$class_4272.method_25402(class_528.java:402)
	at net.minecraft.class_350.method_25402(class_350.java:327)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_312.method_1611(class_312.java:98)
	at net.minecraft.class_437.method_25412(class_437.java:409)
	at net.minecraft.class_312.method_1601(class_312.java:98)
	at net.minecraft.class_312.method_22686(class_312.java:169)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:169)
	at org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81)
	at bre2el.fpsreducer.handler.glfw.InputEventHandler$MouseButtonEventHandler.invoke(InputEventHandler.java:133)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.handler$cmc000$fpsreducer$handleWaitEventsTimeout(RenderSystem.java:2008)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java)
	at net.minecraft.class_310.method_1523(class_310.java:1244)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by Aceplante** [comment]
> I have the same problem, it doesn't crash the game, but it clearly symbolizes that something is broken. **Minecraft version:** _1.20.1_ **Fabric loader version:** _0.16.2_ **Mod version:** _1.0.5+1.20.1 [Refabricated]_
> 
> ```
> Parsing error loading recipe culturaldelights:fermenting/pickle
> com.google.gson.JsonSyntaxException: Unknown item 'c:foods/vegetables/cucumber'
> 	at net.minecraft.class_1869.method_17878(class_1869.java:272)
> 	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
> 	at net.minecraft.class_1869.method_8155(class_1869.java:272)
> 	at net.minecraft.class_1856.method_8107(class_1856.java:160)
> 	at net.minecraft.class_1856.method_8102(class_1856.java:143)
> 	at net.minecraft.class_1856.method_52177(class_1856.java:135)
> 	at dev.sterner.brewinandchewin.common.recipe.KegRecipe$Serializer.readIngredients(KegRecipe.java:180)
> 	at dev.sterner.brewinandchewin.common.recipe.KegRecipe$Serializer.fromJson(KegRecipe.java:150)
> 	at dev.sterner.brewinandchewin.common.recipe.KegRecipe$Serializer.method_8121(KegRecipe.java:144)
> 	at net.minecraft.class_1863.method_17720(class_1863.java:135)
> 	at net.minecraft.class_1863.method_20705(class_1863.java:56)
> 	at net.minecraft.class_1863.method_18788(class_1863.java:35)
> 	at net.minecraft.class_4080.method_18790(class_4080.java:13)
> 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
> 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
> 	at net.minecraft.class_4014.method_18365(class_4014.java:69)
> 	at net.minecraft.class_1255.method_18859(class_1255.java:156)
> 	at net.minecraft.class_4093.method_18859(class_4093.java:23)
> 	at net.minecraft.class_1255.method_16075(class_1255.java:130)
> 	at net.minecraft.class_1255.method_18857(class_1255.java:139)
> 	at net.minecraft.class_310.method_18857(class_310.java:23017)
> 	at net.minecraft.class_7196.method_45694(class_7196.java:188)
> 	at net.minecraft.class_7196.method_41891(class_7196.java:123)
> 	at net.minecraft.class_7196.method_41899(class_7196.java:202)
> 	at net.minecraft.class_7196.handler$zop000$bclib$wt_callFixerOnLoad(class_7196.java:546)
> 	at net.minecraft.class_7196.method_41894(class_7196.java)
> 	at net.minecraft.class_528$class_4272.method_20174(class_528.java:590)
> 	at net.minecraft.class_528$class_4272.method_20164(class_528.java:480)
> 	at net.minecraft.class_528$class_4272.method_25402(class_528.java:402)
> 	at net.minecraft.class_350.method_25402(class_350.java:327)
> 	at net.minecraft.class_4069.method_25402(class_4069.java:38)
> 	at net.minecraft.class_312.method_1611(class_312.java:98)
> 	at net.minecraft.class_437.method_25412(class_437.java:409)
> 	at net.minecraft.class_312.method_1601(class_312.java:98)
> 	at net.minecraft.class_312.method_22686(class_312.java:169)
> 	at net.minecraft.class_1255.execute(class_1255.java:102)
> 	at net.minecraft.class_312.method_22684(class_312.java:169)
> 	at org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81)
> 	at bre2el.fpsreducer.handler.glfw.InputEventHandler$MouseButtonEventHandler.invoke(InputEventHandler.java:133)
> 	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
> 	at org.lwjgl.system.JNI.invokeV(Native Method)
> 	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
> 	at com.mojang.blaze3d.systems.RenderSystem.handler$cmc000$fpsreducer$handleWaitEventsTimeout(RenderSystem.java:2008)
> 	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java)
> 	at net.minecraft.class_310.method_1523(class_310.java:1244)
> 	at net.minecraft.class_310.method_1514(class_310.java:802)
> 	at net.minecraft.client.main.Main.main(Main.java:250)
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
> ```

with the pickle, that always happens unless you have some fermentation mod.
