### ISSUE TITLE
Server Error, Cultural Delights

### ISSUE THREAD

**Issue by null15** [mrsterner/Cultural-Delights-Fabric#38]
`[13:38:39] [main/ERROR]: Parsing error loading recipe culturaldelights:sequenced_assembly/fried_eggplant_pasta
com.google.gson.JsonSyntaxException: Unknown item 'delightfulcreators:incomplete_pasta_dish'
	at net.minecraft.recipe.ShapedRecipe.method_17878(ShapedRecipe.java:272) ~[server-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.recipe.ShapedRecipe.getItem(ShapedRecipe.java:272) ~[server-intermediary.jar:?]
	at net.minecraft.recipe.Ingredient.entryFromJson(Ingredient.java:160) ~[server-intermediary.jar:?]
	at net.minecraft.recipe.Ingredient.fromJson(Ingredient.java:143) ~[server-intermediary.jar:?]
	at net.minecraft.recipe.Ingredient.fromJson(Ingredient.java:135) ~[server-intermediary.jar:?]
	at com.simibubi.create.content.processing.sequenced.SequencedAssemblyRecipeSerializer.readFromJson(SequencedAssemblyRecipeSerializer.java:32) ~[create-fabric-0.5.1-f-build.1417+mc1.20.1.jar:?]
	at com.simibubi.create.content.processing.sequenced.SequencedAssemblyRecipeSerializer.fromJson(SequencedAssemblyRecipeSerializer.java:74) ~[create-fabric-0.5.1-f-build.1417+mc1.20.1.jar:?]
	at com.simibubi.create.content.processing.sequenced.SequencedAssemblyRecipeSerializer.method_8121(SequencedAssemblyRecipeSerializer.java:14) ~[create-fabric-0.5.1-f-build.1417+mc1.20.1.jar:?]
	at net.minecraft.recipe.RecipeManager.deserialize(RecipeManager.java:135) ~[server-intermediary.jar:?]
	at net.minecraft.recipe.RecipeManager.apply(RecipeManager.java:56) ~[server-intermediary.jar:?]
	at net.minecraft.recipe.RecipeManager.apply(RecipeManager.java:35) ~[server-intermediary.jar:?]
	at net.minecraft.resource.SinglePreparationResourceReloader.method_18790(SinglePreparationResourceReloader.java:13) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload.java:69) ~[server-intermediary.jar:?]
	at net.minecraft.util.Util.waitAndApply(Util.java:950) ~[server-intermediary.jar:?]
	at net.minecraft.util.Util.waitAndApply(Util.java:938) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:160) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.16.5.jar:?]`

**Comment by Aceplante** [comment]
> `[13:38:39] [main/ERROR]: Parsing error loading recipe culturaldelights:sequenced_assembly/fried_eggplant_pasta com.google.gson.JsonSyntaxException: Unknown item 'delightfulcreators:incomplete_pasta_dish' at net.minecraft.recipe.ShapedRecipe.method_17878(ShapedRecipe.java:272) ~[server-intermediary.jar:?] at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?] at net.minecraft.recipe.ShapedRecipe.getItem(ShapedRecipe.java:272) ~[server-intermediary.jar:?] at net.minecraft.recipe.Ingredient.entryFromJson(Ingredient.java:160) ~[server-intermediary.jar:?] at net.minecraft.recipe.Ingredient.fromJson(Ingredient.java:143) ~[server-intermediary.jar:?] at net.minecraft.recipe.Ingredient.fromJson(Ingredient.java:135) ~[server-intermediary.jar:?] at com.simibubi.create.content.processing.sequenced.SequencedAssemblyRecipeSerializer.readFromJson(SequencedAssemblyRecipeSerializer.java:32) ~[create-fabric-0.5.1-f-build.1417+mc1.20.1.jar:?] at com.simibubi.create.content.processing.sequenced.SequencedAssemblyRecipeSerializer.fromJson(SequencedAssemblyRecipeSerializer.java:74) ~[create-fabric-0.5.1-f-build.1417+mc1.20.1.jar:?] at com.simibubi.create.content.processing.sequenced.SequencedAssemblyRecipeSerializer.method_8121(SequencedAssemblyRecipeSerializer.java:14) ~[create-fabric-0.5.1-f-build.1417+mc1.20.1.jar:?] at net.minecraft.recipe.RecipeManager.deserialize(RecipeManager.java:135) ~[server-intermediary.jar:?] at net.minecraft.recipe.RecipeManager.apply(RecipeManager.java:56) ~[server-intermediary.jar:?] at net.minecraft.recipe.RecipeManager.apply(RecipeManager.java:35) ~[server-intermediary.jar:?] at net.minecraft.resource.SinglePreparationResourceReloader.method_18790(SinglePreparationResourceReloader.java:13) ~[server-intermediary.jar:?] at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?] at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload.java:69) ~[server-intermediary.jar:?] at net.minecraft.util.Util.waitAndApply(Util.java:950) ~[server-intermediary.jar:?] at net.minecraft.util.Util.waitAndApply(Util.java:938) ~[server-intermediary.jar:?] at net.minecraft.server.Main.main(Main.java:160) ~[server-intermediary.jar:?] at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.5.jar:?] at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.5.jar:?] at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.16.5.jar:?] at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.16.5.jar:?]`

do you have create installed? if not, no wonder, and this can be ignored
